[info]
name = "Avatar Dark"
author = "plaNETwide"

[default]
accent = [0, 255, 255]  # Light Cyan
layer-zero = [0, 0, 0]  # Black
layer-one = [30, 30, 30]  # Dark Gray
text-foreground = [255, 255, 255]  # White

[avatar]
background = "default.layer-zero"
main-element = "default.layer-one"
accent-color = "default.accent"
border-color = "default.accent"
border-thickness = 3

[panel]
background = "default.layer-one"
border = "default.accent"
border-thickness = 2

[button]
background = "default.layer-one"
background-hovered = "default.accent::darker;20"
text = "default.text-foreground"
text-hovered = "default.accent"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [0, 0, 0, 180]
background-blur = false
background-shadow = true
background-shadow-size = 3
background-shadow-color = [0, 0, 0, 100]
