[info]
name = "Blade Runner Light"
author = "plaNETwide"

[default]
accent = [0, 255, 255]  # Neon Cyan
layer-zero = [240, 240, 240]
layer-one = [200, 200, 200]
text-foreground = [10, 10, 10]
text-background = [100, 100, 100]

[panel]
menu = [240, 240, 240]
border = [0, 100, 100]
separator = [0, 100, 100]

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [240, 240, 240, 180]
background-blur = false
background-shadow = true
background-shadow-size = 3
background-shadow-color = [0, 0, 0, 100]
