[info]
name = "Chainsaw Man Dark"
author = "plaNETwide"

[default]
accent = [255, 45, 85]  # Vibrant red
layer-zero = [20, 20, 20]  # Dark gray
layer-one = [35, 35, 35]  # Slightly lighter dark gray
text-foreground = [255, 255, 255]  # White
text-background = [100, 100, 100]  # Medium gray

[panel]
menu = "default.layer-zero"
border = [255, 45, 85]  # Vibrant red
separator = [35, 35, 35]

[module]
background = "default.layer-one"
text = "default.text-foreground"
text-hovered = "default.text-foreground"
description = "default.text-background"
description-hovered = "default.text-foreground"
enabled-background = "default.layer-one::darker"

[button]
background = "default.layer-one"
background-hovered = "default.accent::darker"
text = "default.text-foreground"
text-hovered = "default.text-background"

[tooltip]
background = "default.layer-zero"

[hud]
text-color = [255, 45, 85]  # Vibrant red
text-animation = "pulse"
text-animation-speed = 1.0
text-animation-step = 0.5
text-rainbow-brightness = 0.7
text-rainbow-saturation = 0.9
text-glow = true
background-color = [30, 30, 30, 180]  # Dark translucent
background-blur = true
background-blur-strength = 8
background-shadow = true
background-shadow-size = 8
background-shadow-color = [0, 0, 0, 200]
