[info]
name = "Cyberpunk Dark"
author = "plaNETwide"

[default]
accent = [255, 0, 255]  # Neon Magenta
layer-zero = [0, 0, 0]
layer-one = [30, 30, 30]
text-foreground = [255, 255, 255]
text-background = [50, 50, 50]

[panel]
menu = [0, 0, 0]
border = [100, 0, 100]
separator = [100, 0, 100]

[module]
enabled-background = "default.layer-one::darker"

[button]
background-hovered = "default.accent::darker;30"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [0, 0, 0, 180]
background-blur = true
background-blur-strength = 7
background-shadow = true
background-shadow-size = 7
background-shadow-color = [0, 0, 0, 200]
