[info]
name = "Dragon Ball Dark"
author = "plaNETwide"

[default]
accent = [255, 165, 0]  # Dragon Ball Orange
layer-zero = [20, 20, 20]
layer-one = [40, 40, 40]
text-foreground = [255, 255, 255]
text-background = [80, 80, 80]

[panel]
menu = [20, 20, 20]
border = [255, 165, 0]
separator = [255, 165, 0]

[module]
enabled-background = "default.layer-one::darker"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [20, 20, 20, 180]
background-blur = false
background-shadow = true
background-shadow-size = 5
background-shadow-color = [0, 0, 0, 150]
