[info]
name = "Fight Club Light"
author = "plaNETwide"

[default]
accent = [128, 0, 0]  # Dark Red
layer-zero = [240, 240, 240]
layer-one = [200, 200, 200]
text-foreground = [10, 10, 10]
text-background = [100, 100, 100]

[panel]
menu = [240, 240, 240]
border = [80, 0, 0]
separator = [80, 0, 0]

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [240, 240, 240, 180]
background-blur = false
background-shadow = true
background-shadow-size = 3
background-shadow-color = [0, 0, 0, 100]
