[info]
name = "Howl's Moving Castle Dark"
author = "plaNETwide"

[default]
accent = [255, 165, 0]  # Orange
layer-zero = [10, 10, 20]
layer-one = [40, 40, 60]
text-foreground = [255, 255, 255]
text-background = [80, 80, 120]

[panel]
menu = [10, 10, 20]
border = [40, 40, 60]
separator = [40, 40, 60]

[module]
enabled-background = "default.layer-one::darker"

[button]
background-hovered = "default.accent::darker;30"

[tooltip]
background = "default.layer-one"

[hud]
text-color = [255, 165, 0]  # Orange
text-animation = "pulse"
text-glow = true
background-color = [10, 10, 20, 150]
background-shadow = true
background-shadow-size = 5
background-shadow-color = [0, 0, 0, 255]
