[info]
name = "Hunter x Hunter - Dark"
author = "plaNETwide"

[default]
accent = [0, 255, 0] # Bright green
layer-zero = [20, 20, 20] # Very dark background
layer-one = [40, 40, 40] # Darker grey
text-foreground = [200, 255, 255] # Light cyan
text-background = [80, 80, 80] # Dark grey

[panel]
menu = "default.layer-zero"
border = [0, 255, 0]
separator = [0, 255, 0]

[module]
enabled-background = "default.layer-one::darker"
text = "default.text-foreground"
text-hovered = [255, 255, 255]
description = "default.text-background"

[button]
background = "default.accent"
background-hovered = "default.accent::darker"
text = [255, 255, 255]
text-hovered = [255, 255, 255]

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
text-animation = "pulse"
text-animation-speed = 2.0
text-animation-step = 0.6
text-glow = true
background-color = [20, 20, 20, 200]
background-blur = true
background-blur-strength = 5
background-shadow = true
background-shadow-size = 8
background-shadow-color = [0, 0, 0, 200]
