[info]
name = "Jujutsu Kaisen Light"
author = "plaNETwide"

[default]
accent = [255, 75, 85]  # Soft red with a hint of pink
layer-zero = [245, 245, 245]  # Light gray
layer-one = [230, 230, 230]  # Slightly darker light gray
text-foreground = [30, 30, 30]  # Almost black
text-background = [150, 150, 150]  # Medium gray

[panel]
menu = "default.layer-zero"
border = [255, 75, 85]  # Soft red with a hint of pink
separator = [150, 150, 150]

[module]
background = "default.layer-one"
text = "default.text-foreground"
text-hovered = "default.text-foreground"
description = "default.text-background"
description-hovered = "default.text-foreground"
enabled-background = "default.layer-one::darker"

[button]
background = "default.layer-one"
background-hovered = "default.accent::darker"
text = "default.text-foreground"
text-hovered = "default.text-background"

[tooltip]
background = "default.layer-one"

[hud]
text-color = [255, 75, 85]  # Soft red with a hint of pink
text-animation = "gradient"
text-animation-speed = 1.0
text-animation-step = 0.5
text-gradient-accent = [255, 180, 190]  # Light pink gradient
text-glow = true
background-color = [255, 255, 255, 150]  # Light translucent
background-blur = true
background-blur-strength = 6
background-shadow = true
background-shadow-size = 6
background-shadow-color = [0, 0, 0, 100]
