[info]
name = "The Pianist Dark"
author = "plaNETwide"

[default]
accent = [255, 255, 255]  # White
layer-zero = [0, 0, 0]  # Black
layer-one = [50, 50, 50]  # Dark gray for slight differentiation
text-foreground = [255, 255, 255]  # White
text-background = [100, 100, 100]  # Medium gray

[panel]
menu = "default.layer-zero"
border = [255, 255, 255]  # White
separator = [50, 50, 50]  # Dark gray

[module]
background = "default.layer-one"
text = "default.text-foreground"
text-hovered = "default.text-foreground"
description = "default.text-background"
description-hovered = "default.text-foreground"
enabled-background = "default.layer-one::darker"

[button]
background = "default.layer-one"
background-hovered = "default.layer-one::darker"
text = "default.text-foreground"
text-hovered = "default.text-background"

[tooltip]
background = "default.layer-zero"

[hud]
text-color = [255, 255, 255]  # White
text-animation = "pulse"
text-animation-speed = 1.5
text-animation-step = 0.5
text-rainbow-brightness = 1.0  # Full brightness
text-rainbow-saturation = 0.0  # No saturation (black and white only)
text-gradient-accent = [0, 0, 0]  # Black gradient accent
text-glow = true
background-color = [0, 0, 0, 200]  # Black translucent
background-blur = true
background-blur-strength = 5
background-shadow = true
background-shadow-size = 8
background-shadow-color = [0, 0, 0, 100]
