[info]
name = "Drip"
author = "fenicy"

[default]
accent = [245,27,255]
layer-zero = [15, 15, 35, 190]
layer-one = [30, 30, 50, 190]
corner-radius = 20

[boolean]
circle = [255, 255, 255]

[panel]
menu = "default.layer-zero"
border = [215, 20, 183]
separator = "default.accent"

[tab]
corner-radius = 12

[search]
border-thickness = 3

[slider]
textbox-thickness = 3
circle = [255, 255, 255, 255]

[tooltip]
background = "default.layer-one"

[hud]
text-gradient-accent = [245,27,255]
text-glow = false
