[info]
name = "Naruto - Dark"
author = "plaNETwide"

[default]
accent = [255, 165, 0] # Orange (like Naruto's jumpsuit)
layer-zero = [12, 12, 12]
layer-one = [25, 25, 25]
text-foreground = [255, 255, 255]
text-background = [50, 50, 50]

[panel]
menu = "default.layer-zero"
border = [255, 165, 0]
separator = [255, 165, 0]

[module]
enabled-background = "default.layer-one::darker"
text = "default.text-foreground"
text-hovered = [255, 255, 255]
description = "default.text-background"

[button]
background = "default.accent"
background-hovered = "default.accent::darker"
text = [255, 255, 255]
text-hovered = [255, 255, 255]

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
text-animation = "pulse"
text-animation-speed = 1.5
text-animation-step = 0.5
text-glow = true
background-color = [12, 12, 12, 200]
background-blur = true
background-blur-strength = 5
background-shadow = true
background-shadow-size = 7
background-shadow-color = [0, 0, 0, 180]
