[info]
name = "Owl Light"
author = "plaNETwide"

[default]
accent = [139, 69, 19]  # Saddle Brown
layer-zero = [240, 240, 240]
layer-one = [200, 200, 200]
text-foreground = [34, 34, 34]
text-background = [100, 100, 100]

[panel]
menu = [240, 240, 240]
border = [75, 60, 35]
separator = [75, 60, 35]

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;10"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [240, 240, 240, 180]
background-blur = false
background-shadow = true
background-shadow-size = 3
background-shadow-color = [0, 0, 0, 100]
