[info]
name = "Ponyo Light"
author = "plaNETwide"

[default]
accent = [0, 255, 255]  # Aqua blue
layer-zero = [255, 255, 255]
layer-one = [200, 255, 255]
text-foreground = [20, 20, 40]
text-background = [180, 255, 255]

[panel]
menu = [255, 255, 255]
border = [200, 255, 255]
separator = [200, 255, 255]

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = [0, 255, 255]  # Aqua blue
text-animation = "static"
text-glow = false
background-color = [255, 255, 255, 150]
background-shadow = false
background-shadow-size = 0
background-shadow-color = [0, 0, 0, 0]
