[info]
name = "Tokyo Ghoul Light"
author = "plaNETwide"

[default]
accent = [150, 0, 0]
layer-zero = [240, 240, 240]
layer-one = [200, 200, 200]
text-foreground = [30, 30, 30]
text-background = [180, 180, 180]

[panel]
menu = [240, 240, 240]
border = [200, 200, 200]
separator = [200, 200, 200]

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = [150, 0, 0]
text-animation = "static"
text-glow = false
background-color = [240, 240, 240, 150]
background-shadow = false
background-shadow-size = 0
background-shadow-color = [0, 0, 0, 0]
