[info]
name = "TV Girl Light"
author = "plaNETwide"

[default]
accent = [239, 41, 139]  # Pink (#ef298b)
layer-zero = [240, 240, 240]  # Light Background
layer-one = [210, 210, 210]
text-foreground = [32, 61, 151]  # Deep Blue (#203d97)
text-background = [100, 100, 100]

[panel]
menu = "default.layer-zero"
border = [239, 41, 139]
separator = "default.layer-one"

[module]
enabled-background = "default.layer-one::brighter"

[button]
background-hovered = "default.accent::darker;20"

[tooltip]
background = "default.layer-one"

[hud]
text-color = "default.accent"
background-color = [240, 240, 240, 180]
background-blur = true
background-shadow = true
background-shadow-size = 3
background-shadow-color = [0, 0, 0, 100]
